using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CameraManager : MonoBehaviour
{
    static public CameraManager instance;

    public GameObject target;
    public float moveSpeed;
    private Vector3 targetPosition;

    private MovingObjects movingObj;

    // Start is called before the first frame update
    void Start()
    {
        movingObj = FindObjectOfType<MovingObjects>();
        moveSpeed = movingObj.runSpeed * 350;

        DontDestroyOnLoad(this.gameObject); // 게임 오브젝트 파괴금지

    }
    // Update is called once per frame
    void Update()
    {
        if(target.gameObject != null)
        {
            targetPosition.Set(target.transform.position.x, target.transform.position.y, this.transform.position.z);
            this.transform.position = Vector3.Lerp(this.transform.position, targetPosition, moveSpeed * Time.deltaTime);
        }
    }
}
